services:
  - type: web
    name: contractiq-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ENV
        value: production
      - key: LLM_PROVIDER
        value: groq
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
