"""
PDF Exporter for ContractIQ
==============================
Generates formatted PDF reports from contract analysis results.
Uses ReportLab for PDF generation.
"""

from typing import Dict, Any
from pathlib import Path
from io import BytesIO

from logger import GLOBAL_LOGGER as log

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib import colors
    from reportlab.lib.units import inch
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    log.warning("reportlab not installed. PDF export unavailable.")


def export_pdf(data: Dict[str, Any], output_path: str = None) -> bytes:
    """
    Export analysis results as a formatted PDF report.

    Args:
        data: Analysis/extraction result dictionary
        output_path: Optional file path to save to

    Returns:
        PDF bytes
    """
    if not REPORTLAB_AVAILABLE:
        raise ImportError("reportlab required for PDF export. Install: pip install reportlab")

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=0.5*inch, bottomMargin=0.5*inch)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle("CustomTitle", parent=styles["Title"], fontSize=18, spaceAfter=20)
    story.append(Paragraph("ContractIQ Analysis Report", title_style))
    story.append(Spacer(1, 12))

    key_terms = data.get("key_terms", data.get("extracted_terms", {}))
    analysis = data.get("analysis", {})

    # Summary section
    if analysis:
        story.append(Paragraph("Document Summary", styles["Heading2"]))
        summary = analysis.get("Summary", analysis.get("summary", []))
        if isinstance(summary, list):
            for s in summary:
                story.append(Paragraph(str(s), styles["Normal"]))
        elif summary:
            story.append(Paragraph(str(summary), styles["Normal"]))
        story.append(Spacer(1, 12))

    # Parties
    parties = key_terms.get("parties", [])
    if parties:
        story.append(Paragraph("Parties", styles["Heading2"]))
        party_data = [["Name", "Role"]]
        for p in parties:
            if isinstance(p, dict):
                party_data.append([p.get("name", ""), p.get("role", "")])
        if len(party_data) > 1:
            t = Table(party_data, colWidths=[3*inch, 3*inch])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
            ]))
            story.append(t)
        story.append(Spacer(1, 12))

    # Risk Flags
    risks = key_terms.get("risk_flags", [])
    if risks:
        story.append(Paragraph("Risk Flags", styles["Heading2"]))
        for rf in risks:
            if isinstance(rf, dict):
                level = rf.get("risk_level", "unknown").upper()
                color_map = {"LOW": "#27ae60", "MEDIUM": "#f39c12", "HIGH": "#e74c3c", "CRITICAL": "#c0392b"}
                color = color_map.get(level, "#95a5a6")
                story.append(Paragraph(
                    f'<font color="{color}"><b>[{level}]</b></font> {rf.get("plain_english", "")}',
                    styles["Normal"],
                ))
                story.append(Paragraph(
                    f'<i>Recommendation: {rf.get("recommendation", "N/A")}</i>',
                    styles["Normal"],
                ))
                story.append(Spacer(1, 6))
        story.append(Spacer(1, 12))

    # Key Dates
    story.append(Paragraph("Key Dates", styles["Heading2"]))
    dates_data = [
        ["Field", "Value"],
        ["Effective Date", key_terms.get("effective_date", "Not found")],
        ["Expiration Date", key_terms.get("expiration_date", "Not found")],
        ["Auto Renewal", str(key_terms.get("auto_renewal", "N/A"))],
        ["Governing Law", key_terms.get("governing_law", "Not found")],
        ["Liability Cap", key_terms.get("liability_cap", "Not specified")],
    ]
    t = Table(dates_data, colWidths=[2.5*inch, 3.5*inch])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
    ]))
    story.append(t)
    story.append(Spacer(1, 12))

    # Footer
    story.append(Spacer(1, 24))
    story.append(Paragraph(
        "<i>Generated by ContractIQ — AI-powered contract intelligence</i>",
        styles["Normal"],
    ))

    doc.build(story)
    pdf_bytes = buffer.getvalue()

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "wb") as f:
            f.write(pdf_bytes)
        log.info("PDF exported", path=output_path, size=len(pdf_bytes))

    return pdf_bytes
